name: 'CI'

defaults:
  run:
    shell: bash

on:
  push:
    branches: [main]

env:
  CI: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  ci:
    name: 'Format, Lint, Test, Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup pnpm'
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 'latest'

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: 'Install Dependencies'
        run: pnpm install

      - name: 'Lint'
        run: pnpm lint

      - name: 'Format'
        run: pnpm format

      - name: 'Typecheck'
        run: pnpm typecheck

      - name: 'Build'
        run: pnpm build

      - name: 'Test'
        run: pnpm test
